volumes:
  mongo-data:

services:
  redis:
    image: 'redis:alpine'
    expose:
      - '6379'
  vqg:
    build:
      context: .
      dockerfile: vqg/Dockerfile

  vqa:
    build:
      context: .
      dockerfile: vqa/Dockerfile

  persistence:
    build: 
      context: .
      dockerfile: persistence/Dockerfile
    env_file: .env

  database:
    # build:
    #   context: .
    #   dockerfile: mongo/Dockerfile
    image: mongo
    volumes:
      - mongo-data:/data/db:rw
    expose:
      - 27017
    env_file: .env
